### ISSUE TITLE
Drawable Class missing?

### ISSUE THREAD

**Issue by varomix** [manyminds/gosfml#3]
Hey guys
I'm developing a GUI library and I want to implement a Group object, I found a sample for sfml C++ but it uses **sf.Drawable** which doesn't seem to be available in this version, I could try to add it looking at your code but I'm not that good in GO, still learning.

Is this going to be implemented? or is there a way to use it, maybe I'm not looking in the right place.

Thank you

**Comment by sharpner** [comment]
Sorry this repo is only a mirror of the original one. If you want so sent a PR I will happily merge it :-)
